Controllers/BeurzenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beursspel.Data;
using Beursspel.Models;
using Beursspel.Models.BeursViewModels;
using Beursspel.Models.Beurzen;
using Beursspel.Utilities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Beursspel.Controllers
{
    public class BeurzenController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public BeurzenController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        // GET
        public async Task<IActionResult> Index()
        {
            var beurzen = await BeurzenManager.GetBeurzenAsync();
            Dictionary<int, int> aantallen;
            var userId = User.GetUserId();
            using (var db = new ApplicationDbContext())
            {
                aantallen = await db.Aandelen.Where(x => x.ApplicationUserId == userId)
                    .ToDictionaryAsync(x => x.BeursId, x => x.Aantal);
            }

            return View(new BeursLijstModel
            {
                Beurzen = beurzen,
                AandeelAantallen = aantallen
            });
        }

        private static async Task<ApplicationUser> GetGebruikerWithAandelen(HttpContext httpContext)
        {
            ApplicationUser gebruiker;
            using (var db = new ApplicationDbContext())
            {
                gebruiker = await db.Users.Include(x => x.Aandelen)
                    .SingleAsync(x => x.Id == httpContext.User.GetUserId());
            }
            return gebruiker;
        }

        public async Task<IActionResult> Beurs(string id)
        {
            var errors = TempData.Get<List<string>>("errors");
            if (errors != null)
            {
                var errorType = TempData.Get<string>("errorType");
                foreach (var error in errors)
                {
                    ModelState.AddModelError(errorType, error);
                }
            }
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }
            Beurs beurs;
            if (!int.TryParse(id, out var index))
            {
                beurs = await BeurzenManager.GetBeursMetNaamAsync(id);
            }
            else
            {
                beurs = await GetBeurs(index);
            }
            if (beurs == null)
            {
                return StatusCode(404);
            }
            if (!User.Identity.IsAuthenticated)
                return View(new BeursModel{Beurs = beurs, Aantal = 0});

            var aantal = 0;
            var gebruiker = await GetGebruikerWithAandelen(HttpContext);
            var ah = gebruiker.Aandelen?.FirstOrDefault(x =>
                x.ApplicationUserId == gebruiker.Id && x.BeursId == beurs.BeursId);
            if (ah != null)
                aantal = ah.Aantal;
            var geld = gebruiker.Geld;

            return View(new BeursModel{Beurs = beurs, Aantal = aantal, GebruikerGeld = geld});
        }

        private static async Task<Beurs> GetBeurs(int id)
        {
            return await BeurzenManager.GetBeursAsync(id);
        }

        [HttpPost]
        public async Task<IActionResult> KoopAandelen(BeursModel model)
        {
            if (GeplandeTelMomentenManager.IsMarktDicht)
            {
                return RedirectToAction("Beurs", new {id = model.Beurs.BeursId});
            }
            var gebruiker = await _userManager.GetCurrentUser(HttpContext);
            if (gebruiker == null)
            {
                throw new NullReferenceException("Gebruiker is null");
            }
            if (model.Beurs == null)
            {
                model.Beurs = await GetBeurs(model.BeursId);
            }

            var errors = new List<string>();
            if (!User.IsInRole("Deelnemer"))
            {
                errors.Add("Je bent nog geen deelnemer!");
            }

            var modelValue = model.Aantal * model.Beurs.AandeelPrijs;
            if (model.Aantal <= 0)
            {
                errors.Add("Je moet tenminste 1 aandeel kopen");
            }
            if (modelValue > gebruiker.Geld)
            {
                errors.Add("Je hebt hier niet genoeg geld voor");
            }

            if (errors.Count == 0)
            {
                await gebruiker.KoopAandelen(model.Beurs, model.Aantal);
            }
            TempData.Put("errors", errors);
            TempData.Put("errorType", "Koopfout");
            return RedirectToAction("Beurs", new {id = model.Beurs.BeursId});
        }

        [HttpPost]
        public async Task<IActionResult> VerkoopAandelen(BeursModel model)
        {
            if (GeplandeTelMomentenManager.IsMarktDicht)
            {
                return RedirectToAction("Beurs", new {id = model.Beurs.BeursId});
            }

            var gebruiker = await GetGebruikerWithAandelen(HttpContext);
            if (gebruiker == null)
            {
                throw new NullReferenceException("Gebruiker is null");
            }
            if (model.Beurs == null)
            {
                model.Beurs = await GetBeurs(model.BeursId);
            }

            var errors = new List<string>();
            if (gebruiker.Aandelen == null)
            {
                ModelState.AddModelError("Verkoopfout", "Je hebt hier niet genoeg aandelen in deze beurs voor");
                return RedirectToAction("Beurs", new {id = model.BeursId});
            }

            var aandeelHouder =
                gebruiker.Aandelen.FirstOrDefault(x => x.BeursId == model.BeursId && x.ApplicationUserId == gebruiker.Id);
            if (model.Aantal <= 0)
            {
                errors.Add("Je moet tenminste 1 aandeel verkopen");
            }
            if (aandeelHouder == null || aandeelHouder.Aantal < model.Aantal)
            {
                errors.Add("Je hebt hier niet genoeg aandelen in deze beurs voor");
            }

            if (errors.Count == 0)
            {
                await gebruiker.VerkoopAandelen(model.Beurs, model.Aantal);
            }
            TempData.Put("errors", errors);
            TempData.Put("errorType", "Verkoopfout");
            return RedirectToAction("Beurs", new {id = model.Beurs.BeursId});
        }
    }
}

Controllers/GeplandeTelMomentenController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Beursspel.Data;
using Beursspel.Models;
using Beursspel.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Beursspel.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GeplandeTelMomentenController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var errors = TempData.Get<List<string>>("errors");
            if (errors != null)
            {
                foreach (var error in errors)
                {
                    ModelState.AddModelError("", error);
                }
            }
            using (var db = new ApplicationDbContext())
            {
                var telMomenten = await GeplandeTelMomentenManager.GetGeplandeMomenten();
                return View(new GeplandeTelMomentenModel
                {
                    Geplande = telMomenten
                });
            }
        }

        public async Task<IActionResult> Opslaan(GeplandeTelMomentenModel model)
        {
            if (model.Nieuw != null)
            {
                var fouten = new List<string>();
                if (model.Nieuw.Tijd == default(DateTime))
                {
                    fouten.Add("Tijd mag niet leeg zijn");
                }
                if (string.IsNullOrWhiteSpace(model.Nieuw.Reden))
                {
                    fouten.Add("Reden mag niet leeg zijn");

                }
                if (fouten.Count > 0)
                {
                    TempData.Put("errors", fouten);
                    return RedirectToAction("Index");
                }
                await GeplandeTelMomentenManager.AddTelMoment(model.Nieuw);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Verwijder(string id)
        {
            if (!int.TryParse(id, out var intId))
            {
                return BadRequest();
            }
            await GeplandeTelMomentenManager.DeleteMoment(intId);
            return Ok();
        }
    }
}

Controllers/TelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beursspel.Data;
using Beursspel.Models.TelMomentModels;
using Beursspel.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Beursspel.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TelMomentController : Controller
    {
        public async Task<IActionResult> Index()
        {
            using (var db = new ApplicationDbContext())
            {
                var ls = (await db.TelMomenten.ToListAsync()).OrderByDescending(x => x.Tijd).ToList();
                return View(ls);
            }
        }

        public async Task<IActionResult> Moment(string id)
        {
            if (string.IsNullOrEmpty(id) || !int.TryParse(id, out var i))
            {
                var moment = new TelMomentHouder {Beurzen = new List<TelMomentModel>()};
                foreach (var beurs in await BeurzenManager.GetBeurzenAsync())
                {
                    moment.Beurzen.Add(new TelMomentModel
                    {
                        BeursId = beurs.BeursId,
                        BeursNaam = beurs.Naam,
                    });
                }
                return View(moment);
            }
            using (var db = new ApplicationDbContext())
            {
                var moment = await db.TelMomenten.Include(x => x.Beurzen)
                    .SingleAsync(x => x.TelMomentHouderId == i);
                return View(moment);
            }
        }

        public async Task<IActionResult> Opslaan(TelMomentHouder model)
        {
            if (model.Invoerder == null)
            {
                model.Invoerder = User.Identity.Name;
                model.Tijd = DateTime.Now;
                foreach (var telMomentModel in model.Beurzen)
                {
                    telMomentModel.Tijd = model.Tijd;
                }
                using (var db = new ApplicationDbContext())
                {
                    await db.TelMomenten.AddAsync(model);
                    await db.SaveChangesAsync();
                }
                await Berekeningen.Aanwezigheid.BerekenBeurzen(model);
            }
            else
            {
                using (var db = new ApplicationDbContext())
                {
                    var dbHouder = await db.TelMomenten.Include(x => x.Beurzen)
                        .SingleAsync(x => x.TelMomentHouderId == model.TelMomentHouderId);
                    dbHouder.LaatstBewerkt = DateTime.Now;
                    dbHouder.Bewerker = User.Identity.Name;
                    foreach (var telMomentModel in dbHouder.Beurzen)
                    {
                        var nieuweWaarde = model.Beurzen.FirstOrDefault(x => x.BeursId == telMomentModel.BeursId);
                        if (nieuweWaarde != null && telMomentModel.Aantal != nieuweWaarde.Aantal)
                        {
                            telMomentModel.Aantal = nieuweWaarde.Aantal;
                        }
                    }
                    await db.SaveChangesAsync();
                    await Berekeningen.Aanwezigheid.BerekenBeurzen(dbHouder);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_DataTableScriptsPartial.cshtml
<environment include="Development">
    <script src="lib/jquery-datatables/jquery.dataTables.js"></script>
    <script src="lib/bootstrap-datatables/dataTables.bootstrap.js"></script>
</environment>
<environment exclude="Development">
    <script src="lib/jquery-datatables/jquery.dataTables.min.js"></script>
    <script src="lib/bootstrap-datatables/dataTables.bootstrap.min.js"></script>
</environment>

Views/Shared/_Header.cshtml
<header class="main-header">
  <a href="~/" class="logo">
    <img class="logo-mini" src="~/images/axipr.png" style=" max-width: 40px; margin-left: -10px;margin-top: 5px;"/>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Axipr</b> Beursspel</span>

  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        @if (!User.Identity.IsAuthenticated)
        {
          <li>
            <a href="@Url.Action("Register", "Account")">
              <span class="">Registreren</span>
            </a>
          </li>
        }
        <li class="dropdown user user-menu">
          @if (User.Identity.IsAuthenticated)
          {
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="">@User.Identity.Name</span>
              <span id="waarde-houder" style="margin-left: 10px;"></span>
            </a>
          }
          else
          {
            <a href="@Url.Action("Login", "Account")">
              <span class="">Login</span>
            </a>
          }
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header" style="max-height: 80px;">
              <p>
                @User.Identity.Name
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="@Url.Action("Index", "Manage")" class="btn btn-default btn-flat">Account</a>
              </div>
              <div class="pull-right">
                <a href="@Url.Action("Logout", "Account")" class="btn btn-default btn-flat">Log uit</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <environment include="Development">
    <base href="http://localhost:5000/"/>
  </environment>
  <environment exclude="Development">
    <base href="https://axiprbeursspel.nl/"/>
  </environment>

  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>@ViewData["Title"] - Axipr Beursspel</title>

  <environment include="Development">
    <link rel="stylesheet" href="lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="lib/font-awesome/font-awesome.css"/>
    <link rel="stylesheet" href="lib/admin-lte/css/AdminLTE.css"/>
    <link rel="stylesheet" href="lib/admin-lte/css/skin-blue.css"/>
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" href="lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
    <link rel="stylesheet" href="lib/font-awesome/font-awesome.min.css"/>
    <link rel="stylesheet" href="lib/admin-lte/css/AdminLTE.min.css"/>
    <link rel="stylesheet" href="lib/admin-lte/css/skin-blue.min.css"/>
  </environment>
  <link rel="icon" href="/images/axiprblauw.png">
  @RenderSection("style", required: false)
  <script async src="https://www.googletagmanager.com/gtag/js?id="></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() { dataLayer.push(arguments); }

    gtag('js', new Date());
    gtag('config', '');
  </script>
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  @Html.Partial("_Header")
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    @Html.Partial("_Sidebar")
  </aside>
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        @ViewBag.Title
      </h1>
    </section>
    <section class="content">
      @RenderBody()
    </section>
  </div>
</div>
</body>

<environment include="Development">
  <script src="lib/jquery/jquery.js"></script>
  <script src="lib/jquery/jquery-ui.js"></script>
  <script src="lib/bootstrap/dist/js/bootstrap.js"></script>
  <script src="lib/admin-lte/js/adminlte.js"></script>
  <script src="lib/showdown/showdown.js"></script>
  <script src="js/site.js"></script>
</environment>
<environment exclude="Development">
  <script src="lib/jquery/jquery.min.js"></script>
  <script src="lib/jquery/jquery-ui.min.js"></script>
  <script src="lib/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="lib/admin-lte/js/adminlte.min.js"></script>
  <script src="lib/showdown/showdown.min.js"></script>
  <script src="js/site.min.js"></script>
</environment>
<script>
    function setGebruikerGeld() {
        $.ajax({
            url: '@Url.Action("GetGebruikerGeld","Account")',
            type: "POST",
            success: function(data) {
                if (data.length < 30) {
                    $('#waarde-houder').text("€" + data);
                }
            },
            error: function(xhr, status){
            }
        });
    }
    window.onload = function(){
        setGebruikerGeld();
    };
</script>


@RenderSection("scripts", required: false)

Views/Shared/_Sidebar.cshtml
  <section class="sidebar">

    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">NAVIGATIE</li>
      <li >
        <a href="@Url.Action("Index", "Home")">
          <i class="fa fa-dashboard"></i> <span>Home</span>
        </a>
      </li>
      <li >
        <a href="@Url.Action("Index", "Beurzen")">
          <i class="fa fa-line-chart"></i> <span>Beurzen</span>
        </a>
      </li>
      <li >
        <a href="@Url.Action("Scores", "Home")">
          <i class="fa fa-star"></i> <span>Scores</span>
        </a>
      </li>
      @if (User.IsInRole("Admin"))
      {
        <li class="header">TELMOMENTEN</li>
        <li>
          <a href="@Url.Action("Index", "TelMoment")">
            <i class="fa fa-tasks"></i> <span>Afgelopen</span>
          </a>
        </li>
        <li>
          <a href="@Url.Action("Moment", "TelMoment")">
            <i class="fa fa-plus"></i> <span>Toevoegen</span>
          </a>
        </li>
        <li>
          <a href="@Url.Action("Index", "GeplandeTelMomenten")">
            <i class="fa fa-calendar"></i> <span>Gepland</span>
          </a>
        </li>

        <li class="header">ADMIN</li>
        <li>
          <a href="@Url.Action("Index", "Admin")">
            <i class="fa fa-users"></i> <span>Dashboard</span>
          </a>
        </li>
        <li>
          <a href="@Url.Action("Gebruikers", "Admin")">
            <i class="fa fa-users"></i> <span>Gebruikers</span>
          </a>
        </li>
        <li>
          <a href="@Url.Action("Beurzen", "Admin")">
            <i class="fa fa-bar-chart"></i> <span>Beurzen</span>
          </a>
        </li>
      }
    </ul>
</section>
<!-- /.sidebar -->